### ISSUE TITLE
showcase.js error

### ISSUE THREAD

**Issue by ronaldohoch** [matterport/showcase-sdk-tutorial#11]
hey guys, sorry for asking here, but i don't know where to do it! 
If you provide an official way, my next problem will be there :)

So, sometimes, the matterport don't load the tour and, some errors in console.

![image](https://user-images.githubusercontent.com/2287371/95004153-be06b300-05bd-11eb-9ecc-3278968d3e7e.png)

```
[Locale] 2.252s Loaded phrases - ./locale/strings-en-US.json for en
showcase.js:2 [app-phase] 2.285s {"name":"app","phase":1,"application":2,"phaseTimes":{"0":1601770183099,"1":1601770185319,"2":0,"3":0,"4":0,"5":0},"error":null}
showcase.js:2 [app-phase] 2.288s {"name":"app","phase":2,"application":2,"phaseTimes":{"0":1601770183099,"1":1601770185319,"2":1601770185322,"3":0,"4":0,"5":0},"error":null}
showcase.js:2 [showcase] 2.29s Object
showcase.js:2 [modelurls] 2.443s Using urls version 3
showcase.js:2 [vr-platform-select] 2.459s WebXR disabled DOMException: Failed to execute 'isSessionSupported' on 'XRSystem': Access to the feature "xr" is disallowed by feature policy.
    at https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1601321
    at https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1600780
    at Object.next (https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1600885)
    at https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1599821
    at new Promise (<anonymous>)
    at o (https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1599595)
    at Object.isSessionSupported (https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1601140)
    at https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1603685
    at https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1603025
    at Object.next (https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1603130)
```
```
[viewmodes-data] 3.646s switchToMode mode:2 type:0
showcase.js:2 [app-phase] 58.183s {"name":"app","phase":3,"application":2,"phaseTimes":{"0":1601770183099,"1":1601770185319,"2":1601770185322,"3":1601770241216,"4":0,"5":0},"error":null}
showcase.js:2 [showcase-session] 58.184s First render, model loaded 58.661
showcase.js:2 [vr-platform-select] 58.209s WebXR disabled DOMException: Failed to execute 'isSessionSupported' on 'XRSystem': Access to the feature "xr" is disallowed by feature policy.
    at https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1601321
    at https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1600780
    at Object.next (https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1600885)
    at https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1599821
    at new Promise (<anonymous>)
    at o (https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1599595)
    at Object.isSessionSupported (https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1601140)
    at https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1603685
    at https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1603025
    at Object.next (https://static.matterport.com/showcase/3.1.8.3-0-gea0a6f827/js/showcase.js:2:1603130)
showcase.js:2 [active-reel] 58.391s Reel has 2 items
showcase.js:2 [viewmodes-data] 61.364s switchToMode mode:1 type:2
showcase.js:2 [app-phase] 62.387s {"name":"app","phase":4,"application":2,"phaseTimes":{"0":1601770183099,"1":1601770185319,"2":1601770185322,"3":1601770241216,"4":1601770245421,"5":0},"error":null}
showcase.js:2 [showcase-session] 62.388s Playing, session started 62.865
```

**Comment by OlgaMaslova** [comment]
Same problem! Any advance on that?

**Comment by gbruce** [comment]
Try adding the attribute  allow='xr-spatial-tracking' to the bundle iframe( https://github.com/matterport/showcase-sdk-tutorial/blob/master/index.html#L14).

**Comment by OlgaMaslova** [comment]
Thanks @gbruce , that worked!
